### ISSUE TITLE
idm File Not Working

### ISSUE THREAD

**Issue by Abdullrahman-Dawaliby** [tazihad/idm-linux#1]
Hello Devs
Thanks For Your Great Work But idm File Not Working After I have Tested It With
```
➜  bin idm https://www.google.com
/usr/local/bin/idm: line 13: /home/abdullrahman_dawaliby/.wine/drive_c/Program Files/Internet Download Manager/IDMan.exe: cannot execute binary file: Exec format error
``` 
So ?

**Comment by tazihad** [comment]
@Abdullrahman-Dawaliby kindly check this.
https://zihad.com.bd/posts/how-to-use-idm-in-linux-with-extension/

**Comment by Abdullrahman-Dawaliby** [comment]
i am sorry to be late but i have already knew this from it and i removed wine because of low space so thanks for your hard work
